import SimplePeer from "simple-peer";

/*
Visit index.html#1 from one browser (the initiator) and index.html from another browser (the receiver).

An "offer" will be generated by the initiator. Paste this into the receiver's form and hit submit. The receiver generates an "answer". Paste this into the initiator's form and hit submit.

Now you have a direct P2P connection between two browsers!
*/

const p = new SimplePeer({
  initiator: location.hash === "#1",
  trickle: false
});

p.on("error", err => console.log("error", err));

p.on("signal", data => {
  console.log("SIGNAL", JSON.stringify(data));
  document.querySelector("#outgoing").textContent = JSON.stringify(data);
});

document.querySelector("form").addEventListener("submit", ev => {
  ev.preventDefault();
  p.signal(JSON.parse(document.querySelector("#incoming").value));
});

p.on("connect", () => {
  console.log("CONNECT");
  p.send("whatever" + Math.random());
});

p.on("data", data => {
  console.log("data: " + data);
});
